# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
# Note: php 5.2 & 5.3 are supported only on Precise. 
# See https://docs.travis-ci.com/user/reference/trusty#PHP-images on how to test PHP 5.2 & 5.3 on Precise.
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to a recent 5.4.x version
  - 5.4
  # aliased to a recent 5.5.x version
  - 5.5
  # aliased to a recent 5.6.x version
  - 5.6
  # aliased to a recent 7.x version
  #- 7.0
  # aliased to a recent hhvm version
  #- hhvm  # on Trusty only

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql
  #- DB=pgsql

# optionally set up exclusions and allowed failures in the matrix
#matrix:
  #exclude:
    #- php: hhvm
      #env: DB=mysql
  #allow_failures:
    #- php: 7.0
    #- php: hhvm

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  #- if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS ideaspacevr;" -U postgres; fi
  #- if [[ "$DB" == "pgsql" ]]; then psql -c "create database ideaspacevr;" -U postgres; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS ideaspacevr;" -uroot; fi

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: phpunit --configuration phpunit.xml --coverage-text
