version: "3"
services:
  php:
    build: 
      context: './container/php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: php
  apache:
    build:
      context: './container/apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - db
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: apache
  db:
    image: postgres:${POSTGRES_VERSION:-latest}
    restart: always
    environment:
      TZ: "${APP_TIMEZONE}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - '5432:5432' # Opens port 5432 on the container
    expose:
      - '5432'
    networks:
      - backend
    volumes:
      - data:/var/lib/postgresql/data
    container_name: postgresql
  phppgadmin:
    image: dockage/phppgadmin:latest
    restart: always
    ports:
        - "${PHP_PG_ADMIN_PORT:-8080}:80"
    environment:
        PHP_PG_ADMIN_SERVER_HOST: "db"
        PHP_PG_ADMIN_SERVER_PORT: "${DB_PORT}"
        PHP_PG_ADMIN_SERVER_DEFAULT_DB: "${DB_NAME}"
    networks:
      - backend
    container_name: phppgadmin   

networks:
  frontend:
  backend:
volumes:
    data:
# useradd -
  # chown -R user:group /var/www/html
  # chomod -R 774 /var/www/